import Link from "next/link";

const rules=[
 {number:"1",enTitle:"Set up the screens",en:"Open Main Board on the shared screen. Give the Red and Blue private links only to their own Spymasters. Spymasters can see card identities; guessers cannot.",hiTitle:"स्क्रीन तैयार करें",hi:"Main Board को सभी खिलाड़ियों की साझा स्क्रीन पर खोलें। Red और Blue Spymaster की निजी लिंक केवल संबंधित Spymaster को दें। Spymaster कार्ड की पहचान देख सकते हैं; guessing players नहीं।"},
 {number:"2",enTitle:"Know the board",en:"Every board has 25 cards: 9 cards for the starting team, 8 for the other team, 7 neutral cards, and 1 assassin. The starting team is chosen at random.",hiTitle:"बोर्ड को समझें",hi:"हर बोर्ड में 25 कार्ड होते हैं: शुरू करने वाली टीम के 9, दूसरी टीम के 8, 7 neutral कार्ड और 1 assassin। शुरू करने वाली टीम अपने-आप चुनी जाती है।"},
 {number:"3",enTitle:"Give a clue",en:"Only the active team’s Spymaster gives a clue. Use one meaningful word and a number from 1 to 9 to suggest how many of your team’s cards are connected. Keep the clue fair—do not point, gesture, spell, or use an active card word as the clue.",hiTitle:"संकेत दें",hi:"सिर्फ सक्रिय टीम का Spymaster संकेत देता है। एक अर्थपूर्ण शब्द और 1 से 9 तक की संख्या दें, जिससे आपकी टीम को जुड़े हुए कार्ड समझ आएँ। संकेत निष्पक्ष रखें—इशारा, gesture, spelling या बोर्ड के किसी सक्रिय शब्द को clue के रूप में इस्तेमाल न करें।"},
 {number:"4",enTitle:"Make guesses",en:"After a clue, the Main Board guesses one card at a time. A correct team card lets the team keep guessing. The guess allowance is the clue number plus one; the team may also pass early.",hiTitle:"अनुमान लगाएँ",hi:"संकेत के बाद Main Board एक-एक कार्ड चुनता है। अपनी टीम का सही कार्ड मिलने पर टीम आगे guess कर सकती है। guesses की सीमा clue number + 1 होती है; टीम चाहें तो जल्दी pass भी कर सकती है।"},
 {number:"5",enTitle:"End a turn or the game",en:"Choosing a neutral or opposing-team card immediately ends the turn. Choosing the assassin immediately ends the game and gives victory to the other team. A team wins by revealing all of its own cards first.",hiTitle:"टर्न या खेल समाप्त करें",hi:"Neutral या दूसरी टीम का कार्ड चुनते ही टर्न समाप्त हो जाता है। Assassin चुनते ही खेल समाप्त होता है और दूसरी टीम जीतती है। अपनी टीम के सभी कार्ड पहले खोलने वाली टीम जीतती है।"},
 {number:"6",enTitle:"Before the first clue",en:"If everyone agrees the layout needs another mix, Main Board can use Shuffle Board. It keeps the same room, links, words, and card counts. Once any clue is given or card is revealed, the board cannot be shuffled.",hiTitle:"पहले clue से पहले",hi:"अगर सभी को board फिर से मिलाना हो, तो Main Board से Shuffle Board चुनें। इससे वही room, links, words और card counts रहते हैं। कोई clue देने या कार्ड खुलने के बाद board shuffle नहीं किया जा सकता।"},
];

export default function RulesPage(){return <main className="mx-auto min-h-screen max-w-4xl p-4 sm:p-6"><header className="flex items-start justify-between gap-4"><div><p className="text-sm text-amber-400">HOUSE PARTY TIME</p><h1 className="text-3xl font-black sm:text-4xl">How to Play <span className="text-stone-500">/</span> कैसे खेलें</h1><p className="mt-2 max-w-2xl text-stone-400">A bilingual guide for this three-screen word-association game.</p></div><Link className="bg-stone-700" href="/">Home</Link></header><section className="mt-6 rounded-xl border border-amber-400/30 bg-amber-400/10 p-4"><h2 className="font-bold text-amber-300">Quick start / जल्दी शुरू करें</h2><p className="mt-1 text-sm text-stone-200">Create a room, choose a pack, share the three screens, and start from Main Board. The two Spymasters must keep their screens private.</p></section><div className="mt-5 space-y-3">{rules.map(rule=><section key={rule.number} className="rounded-xl border border-stone-800 bg-stone-900 p-4"><div className="flex gap-3"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-amber-400 font-black text-stone-950">{rule.number}</span><div className="grid gap-4 md:grid-cols-2"><div><h2 className="font-bold">{rule.enTitle}</h2><p className="mt-1 text-sm leading-6 text-stone-300">{rule.en}</p></div><div lang="hi"><h2 className="font-bold">{rule.hiTitle}</h2><p className="mt-1 text-sm leading-6 text-stone-300">{rule.hi}</p></div></div></div></section>)}</div><p className="mt-6 text-center text-xs text-stone-500">House Party Time is an original game experience and is not affiliated with Codenames or Czech Games Edition.</p></main>}
