"use client";
import {useCallback,useEffect,useState} from "react";
import {supabase} from "../lib/supabase";
import type {Session,State,Team} from "../lib/types";
import {HINDI_WORDS} from "../lib/words";

export default function Game({session,onInvalidSession}:{session:Session;onInvalidSession:()=>void}) {
 const [state,setState]=useState<State|null>(null),[error,setError]=useState(""),[clue,setClue]=useState(""),[count,setCount]=useState(1),[pending,setPending]=useState(false),[syncStatus,setSyncStatus]=useState<"connecting"|"connected"|"fallback">("connecting"),[copied,setCopied]=useState(false);
 const refresh=useCallback(async()=>{const r=await supabase.rpc("room_state",{p_code:session.code,p_player_id:session.playerId,p_token:session.token});if(r.error){if(/Invalid room session/i.test(r.error.message))onInvalidSession();else setError(r.error.message);return false}setState(r.data);return true},[onInvalidSession,session]);
 useEffect(()=>{void refresh();const channel=supabase.channel("room:"+session.code).on("broadcast",{event:"changed"},()=>void refresh()).on("broadcast",{event:"room_changed"},()=>void refresh()).subscribe(status=>{setSyncStatus(status==="SUBSCRIBED"?"connected":"fallback")});return()=>{supabase.removeChannel(channel)}},[refresh,session.code]);
 useEffect(()=>{if(syncStatus==="connected")return;const timer=window.setInterval(()=>void refresh(),10000);return()=>window.clearInterval(timer)},[refresh,syncStatus]);
 async function act(fn:string,extra:Record<string,unknown>={}){if(pending)return;setError("");setPending(true);const r=await supabase.rpc(fn,{p_code:session.code,p_player_id:session.playerId,p_token:session.token,...extra});setPending(false);if(r.error)setError(r.error.message);else {await supabase.channel("room:"+session.code).send({type:"broadcast",event:"changed",payload:{}});void refresh()}}
 async function copyLink(){try{await navigator.clipboard.writeText(location.origin+location.pathname+"?room="+state?.code);setCopied(true);window.setTimeout(()=>setCopied(false),2000)}catch{setError("Could not copy the room link.")}}
 if(!state)return <main className="p-8">कमरा खुल रहा है… {error}</main>;
 const me=state.players.find(p=>p.id===session.playerId), canGuess=state.status==="playing"&&me?.team===state.active_team&&!me.is_spymaster;
 const team=(t:Team)=>state.players.filter(p=>p.team===t);
 return <main className="mx-auto max-w-6xl p-4"><header className="mb-5 flex justify-between gap-3"><div><h1 className="text-3xl font-black">संकेत <small className="text-amber-400">{state.code}</small></h1><p className="text-sm text-stone-400">Share this code with friends {syncStatus==="fallback"&&"• Reconnecting…"}</p></div><button className="bg-stone-700" onClick={copyLink}>{copied?"लिंक कॉपी हो गया":"लिंक कॉपी करें"}</button></header>
 {state.status==="lobby"?<Lobby state={state} me={me} team={team} act={act}/>:<><section className="mb-4 rounded-xl bg-stone-900 p-4"><b className={state.active_team==="red"?"text-red-400":"text-blue-400"}>{state.status==="finished"?"खेल खत्म":state.active_team==="red"?"🔴 लाल टीम की बारी":"🔵 नीली टीम की बारी"}</b>{state.clue&&<p className="mt-2 text-xl">इशारा: <strong>{state.clue} — {state.clue_number}</strong> <span className="text-sm text-stone-400">({state.guesses_left} left)</span></p>}</section>
 {me?.is_spymaster&&me.team===state.active_team&&state.status==="playing"&&!state.clue&&<form className="mb-4 flex gap-2" onSubmit={e=>{e.preventDefault();void act("submit_clue",{p_clue:clue,p_count:count})}}><input value={clue} onChange={e=>setClue(e.target.value)} disabled={pending} placeholder="इशारा" required/><input className="w-20" min="1" max="9" type="number" value={count} disabled={pending} onChange={e=>setCount(+e.target.value)}/><button disabled={pending} className="bg-amber-400 text-stone-900">इशारा दें</button></form>}
 <section className="grid grid-cols-2 gap-2 sm:grid-cols-5">{state.cards.map(c=>{const color=c.revealed?c.type:(me?.is_spymaster?c.type:undefined);return <button key={c.id} disabled={pending||!canGuess||!state.clue||c.revealed||state.status!=="playing"} onClick={()=>void act("guess_card",{p_card_id:c.id})} className={(color==="red"?"bg-red-700":color==="blue"?"bg-blue-700":color==="neutral"?"bg-stone-500":color==="assassin"?"bg-stone-950 ring-2 ring-amber-500":"bg-amber-100 text-stone-900")+" min-h-24 text-lg"}>{c.word.hi}<span className="block text-xs opacity-70">{c.word.roman}</span></button>})}</section>
 <div className="mt-5 flex gap-2">{canGuess&&state.clue&&<button disabled={pending} className="bg-stone-700" onClick={()=>void act("pass_turn")}>बारी छोड़ें</button>}{state.status==="finished"&&me?.is_host&&<button disabled={pending} className="bg-amber-400 text-stone-900" onClick={()=>void act("rematch",{p_words:HINDI_WORDS})}>नया खेल</button>}</div></>}{error&&<p className="mt-4 text-red-400">{error}</p>}</main>
}
function Lobby({state,me,team,act}:{state:State;me:any;team:(t:Team)=>any[];act:(f:string,a?:Record<string,unknown>)=>void}){const box=(t:Team)=>{const players=team(t);return <div className={(t==="red"?"bg-red-950/40":"bg-blue-950/40")+" rounded-xl p-4"}><h2 className="font-bold">{t==="red"?"🔴 लाल टीम":"🔵 नीली टीम"}</h2>{players.map(p=><p key={p.id}>{p.nickname} {p.is_host&&"⭐"} {p.is_spymaster&&"🕵️"}</p>)}<button className="mt-3 bg-stone-800 text-sm" onClick={()=>void act("set_team",{p_team:t})}>इस टीम में जाएँ</button>{me?.is_host&&<button className="ml-2 mt-3 bg-stone-800 text-sm" disabled={!players.length} onClick={()=>void act("set_spymaster",{p_target_id:players[0]?.id,p_team:t})}>पहले को जासूस बनाएँ</button>}</div>};return <><p className="mb-4 rounded-lg bg-stone-900 p-3">लॉबी में {state.players.length} खिलाड़ी हैं। हर टीम के लिए एक जासूस चुनें।</p><section className="grid gap-3 sm:grid-cols-2">{box("red")}{box("blue")}</section>{me?.is_host&&<button className="mt-5 bg-amber-400 text-stone-900" onClick={()=>void act("start_game",{p_words:HINDI_WORDS})}>खेल शुरू करें</button>}</>}
