"use client";
import {useCallback,useEffect,useState} from "react";
import Link from "next/link";
import {supabase,supabaseConfigurationError} from "../lib/supabase";
import {clearRoleSession,getRoleSession,saveRoleSession} from "../lib/role-session";
import {getWordPack} from "../lib/words";
import type {CardType,RoleRoomState,RoomRole} from "../lib/types";

type SpyRole="spymaster_1"|"spymaster_2";
const expectedTeam=(role:SpyRole)=>role==="spymaster_1"?"red":"blue";
const teamLabel=(team:"red"|"blue")=>team==="red"?"Red":"Blue";
export default function RoleGame({code,role}:{code:string;role:RoomRole}){const roomCode=code.toUpperCase();const isSpy=role!=="main_board";const spyRole=isSpy?role as SpyRole:null;const [token,setToken]=useState<string|null>(null),[state,setState]=useState<RoleRoomState|null>(null),[error,setError]=useState(""),[pending,setPending]=useState(false),[sync,setSync]=useState("connecting"),[clue,setClue]=useState(""),[count,setCount]=useState(1);
 useEffect(()=>{if(!spyRole)return;const fragment=new URLSearchParams(window.location.hash.slice(1)).get("token");if(fragment){setToken(fragment);window.history.replaceState(null,"",window.location.pathname+window.location.search)}else setToken(getRoleSession(roomCode,spyRole)?.token??null)},[roomCode,spyRole]);
 const refresh=useCallback(async()=>{if(supabaseConfigurationError){setError(supabaseConfigurationError);return false}if(isSpy&&!token)return false;try{const {data,error}=await supabase.rpc("room_state_for_role",{p_code:roomCode,p_role_token:token});if(error||!data){if(spyRole)clearRoleSession(roomCode,spyRole);setError(error?.message??"Could not load room.");return false}const next=data as RoleRoomState;if(next.role!==role){if(spyRole)clearRoleSession(roomCode,spyRole);setError("Spymaster access is invalid or has expired.");return false}if(spyRole&&token)saveRoleSession({roomCode,role:spyRole,token});setState(next);setError("");return true}catch{setError("Could not reach Supabase. Check the project URL, network access, and that the project is running.");return false}},[isSpy,role,roomCode,spyRole,token]);
 useEffect(()=>{void refresh();const channel=supabase.channel("room:"+roomCode).on("broadcast",{event:"room_changed"},()=>void refresh()).on("broadcast",{event:"changed"},()=>void refresh()).subscribe(status=>setSync(status==="SUBSCRIBED"?"connected":"reconnecting"));const focus=()=>void refresh();window.addEventListener("focus",focus);return()=>{window.removeEventListener("focus",focus);supabase.removeChannel(channel)}},[refresh,roomCode]);
 useEffect(()=>{if(sync==="connected")return;const id=window.setInterval(()=>void refresh(),10000);return()=>window.clearInterval(id)},[refresh,sync]);
 async function action(fn:string,args:Record<string,unknown>={}){if(pending)return;setPending(true);setError("");const {error}=await supabase.rpc(fn,{p_code:roomCode,...args});setPending(false);if(error)setError(error.message);else void refresh()}
 if(isSpy&&!token)return <AccessError code={roomCode} text="Spymaster access is invalid or has expired."/>;
 if(!state)return <AccessError code={roomCode} text={error||"Loading room…"}/>;
 const spyCanClue=spyRole&&state.status==="playing"&&state.active_team===expectedTeam(spyRole)&&!state.clue;
 const canShuffle=role==="main_board"&&state.status==="playing"&&!state.clue&&state.cards.every(card=>!card.revealed);
 return <main className="mx-auto min-h-screen max-w-6xl p-4 sm:p-6"><header className="mb-5 flex items-start justify-between gap-3"><div><p className="text-sm text-amber-400">{role==="main_board"?"MAIN BOARD":`${expectedTeam(spyRole!)} SPYMASTER`}</p><h1 className="text-2xl font-black sm:text-3xl">House Party Time <small className="text-amber-400">{state.code}</small></h1><p className="text-sm text-stone-400">{sync==="reconnecting"?"Reconnecting…":role==="main_board"?"Shared team board":"Private screen"}</p></div><div className="flex shrink-0 gap-2">{role==="main_board"&&<Link className="rounded-lg bg-stone-700 px-4 py-2 font-semibold" href="/rules">Rules</Link>}<Link className="rounded-lg bg-stone-700 px-4 py-2 font-semibold" href="/">Home</Link></div></header><RoleGuide role={role} pack={getWordPack(state.word_pack).name}/>
 {state.status==="lobby"?<Lobby state={state} main={role==="main_board"} pending={pending} start={()=>void action("role_start_game",{p_words:getWordPack(state.word_pack).words})}/>:<><section className="mb-4 rounded-xl bg-stone-900 p-4"><b className={state.active_team==="red"?"text-red-400":"text-blue-400"}>{state.status==="finished"?`${teamLabel(state.winner as "red"|"blue")} Team wins!`:`${teamLabel(state.active_team)} Team's turn`}</b>{state.clue?<p className="mt-2 text-xl">Clue: <strong>{state.clue} — {state.clue_number}</strong> <span className="text-sm text-stone-400">({state.guesses_left} left)</span></p>:state.status==="playing"&&<p className="mt-2 text-stone-400">Waiting for {teamLabel(state.active_team)} Spymaster…</p>}</section>
 {spyCanClue&&<form className="mb-4 flex flex-wrap gap-2" onSubmit={e=>{e.preventDefault();void action("role_submit_clue",{p_spymaster_token:token,p_clue:clue,p_count:count})}}><input disabled={pending} className="min-w-40 flex-1" value={clue} onChange={e=>setClue(e.target.value)} placeholder="One-word clue" required/><input disabled={pending} className="w-20" type="number" min="1" max="9" value={count} onChange={e=>setCount(+e.target.value)}/><button disabled={pending} className="bg-amber-400 text-stone-950">Submit Clue</button></form>}
 {isSpy&&!spyCanClue&&state.status==="playing"&&!state.clue&&<p className="mb-4 text-stone-400">Waiting for {teamLabel(state.active_team)} Team&apos;s turn.</p>}
 <Board state={state} secret={isSpy} disabled={pending||role!=="main_board"||!state.clue||state.status!=="playing"} onGuess={id=>void action("role_guess_card",{p_card_id:id})}/>
 {role==="main_board"&&<div className="mt-5 flex flex-wrap gap-2">{canShuffle&&<button disabled={pending} className="bg-stone-700" onClick={()=>{if(window.confirm("Shuffle the board for everyone? This is only available before the first clue or guess."))void action("role_shuffle_board")}}>Shuffle Board</button>}{state.status==="playing"&&state.clue&&<button disabled={pending} className="bg-stone-700" onClick={()=>void action("role_pass_turn")}>Pass Turn</button>}{state.status==="finished"&&<button disabled={pending} className="bg-amber-400 text-stone-950" onClick={()=>void action("role_rematch",{p_words:getWordPack(state.word_pack).words})}>Rematch</button>}</div>}</>}{error&&<p className="mt-4 text-red-400">{error}</p>}</main>}
function Lobby({state,main,pending,start}:{state:RoleRoomState;main:boolean;pending:boolean;start:()=>void}){const pack=getWordPack(state.word_pack);return <section className="rounded-xl bg-stone-900 p-5"><h2 className="text-xl font-bold">Room {state.code}</h2><p className="mt-2 text-amber-400">{pack.name} pack</p><p className="mt-2 text-stone-400">Private Spymaster links are shared separately. Players organize teams verbally.</p>{main?<button disabled={pending} className="mt-5 bg-amber-400 text-stone-950" onClick={start}>Start Game</button>:<p className="mt-5 text-stone-400">Waiting for the Main Board to start the game.</p>}</section>}
function Board({state,secret,disabled,onGuess}:{state:RoleRoomState;secret:boolean;disabled:boolean;onGuess:(id:number)=>void}){return <section className="grid grid-cols-2 gap-2 sm:grid-cols-5">{state.cards.map(card=>{const type="type" in card?card.type:undefined;const color=card.revealed?type:(secret?type:undefined);const classes=colorClass(color);return <button key={card.id} disabled={disabled||card.revealed} onClick={()=>onGuess(card.id)} className={`${classes} min-h-20 px-2 text-base sm:min-h-24 sm:text-lg`}>{card.word.hi}<span className="block text-xs opacity-70">{card.word.roman}</span></button>})}</section>}
function colorClass(type:CardType|undefined){return type==="red"?"bg-red-700":type==="blue"?"bg-blue-700":type==="neutral"?"bg-stone-500":type==="assassin"?"bg-stone-950 ring-2 ring-amber-500":"bg-amber-100 text-stone-900"}
function RoleGuide({role,pack}:{role:RoomRole;pack:string}){const text=role==="main_board"?"Keep this screen visible for guessers. Card colors remain hidden here.":"Keep this screen private. You can see every card type; give your team one-word clues when it is your turn.";return <section className="mb-4 rounded-xl border border-stone-800 bg-stone-900/70 p-3 text-sm text-stone-300"><span className="font-bold text-amber-400">{pack}</span><span className="mx-2 text-stone-600">•</span>{text}</section>}
function AccessError({code,text}:{code:string;text:string}){return <main className="mx-auto flex min-h-screen max-w-md flex-col justify-center gap-4 p-6"><h1 className="text-3xl font-black">House Party Time</h1><p className="text-stone-400">{text}</p><Link className="rounded-lg bg-stone-700 px-4 py-2 font-semibold" href={`/room/${code}`}>Open Main Board</Link></main>}
